"""create pvp_seasons

Revision ID: 720b571998e1
Revises: 
Create Date: 2025-10-01 10:49:13.318448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720b571998e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pvp_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_json', sa.JSON(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='uq_pvp_seasons_id')
    )
    op.create_index(op.f('ix_pvp_seasons_id'), 'pvp_seasons', ['id'], unique=False)
    op.create_index(op.f('ix_pvp_seasons_is_current'), 'pvp_seasons', ['is_current'], unique=False)
    op.create_index(op.f('ix_pvp_seasons_updated_at'), 'pvp_seasons', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pvp_seasons_updated_at'), table_name='pvp_seasons')
    op.drop_index(op.f('ix_pvp_seasons_is_current'), table_name='pvp_seasons')
    op.drop_index(op.f('ix_pvp_seasons_id'), table_name='pvp_seasons')
    op.drop_table('pvp_seasons')
    # ### end Alembic commands ###
